[package]
name = "crawler"
version = "0.1.0"
edition = "2021"

[dependencies]
csv = "1.2.1"
tar = "0.4.38"
serde = "1.0.102"
serde_json = "1.0.41"
serde_derive = "1.0.163"
libflate = "1.4.0"
semver = { version="0.9.0", features=["ci"] }
rayon = "1"
